name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Publish
      run: dotnet publish KhamsaCourseProject/KhamsaCourseProject -c Release
