name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore KhamsaCourseProject/KhamsaCourseProject/KhamsaCourseProject.csproj
    - name: Publish
      run: dotnet publish KhamsaCourseProject/KhamsaCourseProject -c Release
